import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import clsx from "clsx";
import Navbar from "@/components/navbar/navbar";
import ModalHandler from "@/components/modals/modal-handler";

const font = localFont({
  src: [
    {
      path: "../public/fonts/OmnesLatin-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/OmnesLatin-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-omens",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wolt Picker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "flex flex-col items-center",
          font.variable,
          inter.className
        )}
      >
        <Navbar />
        <div className="w-full max-w-[1600px] px-4 pb-8 pt-[5.5rem] md:px-6 min-h-screen flex flex-col">
          {children}
        </div>
        <ModalHandler />
      </body>
    </html>
  );
}
